// Generated by gencpp from file extended_object_detection/ExtractedInfo.msg
// DO NOT EDIT!


#ifndef EXTENDED_OBJECT_DETECTION_MESSAGE_EXTRACTEDINFO_H
#define EXTENDED_OBJECT_DETECTION_MESSAGE_EXTRACTEDINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace extended_object_detection
{
template <class ContainerAllocator>
struct ExtractedInfo_
{
  typedef ExtractedInfo_<ContainerAllocator> Type;

  ExtractedInfo_()
    : keys()
    , values()  {
    }
  ExtractedInfo_(const ContainerAllocator& _alloc)
    : keys(_alloc)
    , values(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _keys_type;
  _keys_type keys;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _values_type;
  _values_type values;





  typedef boost::shared_ptr< ::extended_object_detection::ExtractedInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::extended_object_detection::ExtractedInfo_<ContainerAllocator> const> ConstPtr;

}; // struct ExtractedInfo_

typedef ::extended_object_detection::ExtractedInfo_<std::allocator<void> > ExtractedInfo;

typedef boost::shared_ptr< ::extended_object_detection::ExtractedInfo > ExtractedInfoPtr;
typedef boost::shared_ptr< ::extended_object_detection::ExtractedInfo const> ExtractedInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::extended_object_detection::ExtractedInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::extended_object_detection::ExtractedInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::extended_object_detection::ExtractedInfo_<ContainerAllocator1> & lhs, const ::extended_object_detection::ExtractedInfo_<ContainerAllocator2> & rhs)
{
  return lhs.keys == rhs.keys &&
    lhs.values == rhs.values;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::extended_object_detection::ExtractedInfo_<ContainerAllocator1> & lhs, const ::extended_object_detection::ExtractedInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace extended_object_detection

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::extended_object_detection::ExtractedInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::extended_object_detection::ExtractedInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::extended_object_detection::ExtractedInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::extended_object_detection::ExtractedInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::extended_object_detection::ExtractedInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::extended_object_detection::ExtractedInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::extended_object_detection::ExtractedInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8dcfc845da12061fdc33c889527f840c";
  }

  static const char* value(const ::extended_object_detection::ExtractedInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8dcfc845da12061fULL;
  static const uint64_t static_value2 = 0xdc33c889527f840cULL;
};

template<class ContainerAllocator>
struct DataType< ::extended_object_detection::ExtractedInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "extended_object_detection/ExtractedInfo";
  }

  static const char* value(const ::extended_object_detection::ExtractedInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::extended_object_detection::ExtractedInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] keys\n"
"string[] values\n"
;
  }

  static const char* value(const ::extended_object_detection::ExtractedInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::extended_object_detection::ExtractedInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.keys);
      stream.next(m.values);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExtractedInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::extended_object_detection::ExtractedInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::extended_object_detection::ExtractedInfo_<ContainerAllocator>& v)
  {
    s << indent << "keys[]" << std::endl;
    for (size_t i = 0; i < v.keys.size(); ++i)
    {
      s << indent << "  keys[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.keys[i]);
    }
    s << indent << "values[]" << std::endl;
    for (size_t i = 0; i < v.values.size(); ++i)
    {
      s << indent << "  values[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.values[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXTENDED_OBJECT_DETECTION_MESSAGE_EXTRACTEDINFO_H
